spring.application.name=servicio_mensajeria

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:kafka1:9092,kafka2:9093}
spring.kafka.consumer.group-id=grupo-mensajeria
spring.kafka.consumer.auto-offset-reset=earliest