FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY . .

RUN sed -i 's/\r//' gradlew && chmod +x gradlew

RUN ./gradlew :servicio_mensajeria:bootJar --no-daemon -x test

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

COPY --from=builder /app/servicio_mensajeria/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]