FROM gradle:8.7-jdk21 AS builder
WORKDIR /app
COPY . .
RUN gradle :epersgeist:bootJar --stacktrace --no-daemon

FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=builder /app/epersgeist/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]