FROM gradle:8.7-jdk21 AS builder

WORKDIR /app
COPY . .

RUN gradle :servicio_mensajeria:bootJar --stacktrace --no-daemon

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

COPY --from=builder /app/servicio_mensajeria/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]