spring.application.name=servicio_probabilidad

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:kafka:9092}
spring.kafka.consumer.group-id=grupo-probabilidad
spring.kafka.consumer.auto-offset-reset=earliest