spring.application.name=servicio_temperatura

# Kafka (los brokers dentro de docker)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:kafka1:9092}
logging.level.org.apache.kafka=INFO
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# PostgreSQL (base de datos LOCAL del host)
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/epersgeist
spring.datasource.username=postgres
spring.datasource.password=postgres
